### ISSUE TITLE
Las clases que se use el juego debe ocultar las dependencias de las librerías

### ISSUE THREAD

**Issue by Dewo2000** [P3-22-23-Grupo6/Motor#73]
- [x] LmVector
- [x] InputManager

**Comment by ivo-hr** [comment]
Creado wrapper de LMVector llamado 3DUnits: incluye todos los métodos útiles, compatibilidad con lmVector y todas las librerías están ocultas.
Se puede ver en [esta rama](https://github.com/P3-22-23-Grupo6/Motor.git). Estos cambios ocurrieron con [este commit](https://github.com/P3-22-23-Grupo6/Motor/commit/be4c624f89f6d3916cffaa68fe6e67ad4675a1a5).

**Comment by ivo-hr** [comment]
Wrapper anterior depreciado a cambio de convertir LMVector en el principal, sacando las conversiones (gracias @Dewo2000 )

Creado LMInputs, que incluye todos los keycodes y scancodes relevantes. Teclas de función, como volumeup y volumedown, han sido eliminados debido a conflictos con windows 10 y 11.
